#!/bin/bash

hooks_dir="$(dirname "$0")"
# Include helpers
source "$hooks_dir/helpers.sh"

if is_systemd
    then
        service glusterfs-server start
    else
        service glusterfs-server restart
fi